_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: KlokanTech, MapBox, Natural Earth Data
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 0.5713
  - 45.6908
  - 5
description: Style converted from TileMill's Geographical Class made from Natural Earth data processed by MapBox.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 10
minzoom: 0
name: Countries
source: "tmsource:///Users/klokan/Projects/vector-tiles-sample/countries.tm2source"
styles: 
  - style.mss
  - labels.mss
template: ''
