_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: KlokanTech, MapBox, Natural Earth Data
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 0
  - 0
  - 2
description: Style converted from TileMill's Geographical Class made from Natural Earth data processed by MapBox.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 10
minzoom: 0
name: Countries
source: "mapbox:///klokantech.97cbd1e1"
styles: 
  - style.mss
  - labels.mss
template: ''
